apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-local.fullname" . }}
  labels:
    {{- include "nginx-local.labels" . | nindent 4 }}
  namespace: terraform 

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-local.selectorLabels" . | nindent 4 }}
  