apiVersion: apps/v1
kind: Deployment
  name: {{- .Values.customBlock.auther.name }}
  job: {{- .Values.customBlock.auther.job }}
  {{.Values.customBlock.auther.adress }}
  {{.Values.customBlock.auther.adress | default "i am not null" }}
  {{.Values.customBlock.auther.email | default "i am not null" }}
  {{.Values.customBlock.auther.adress | default "i am not null" | upper }}
  {{.Values.customBlock.auther.email | default "i am not null" | upper }}
  {{.Values.customBlock.auther.email | default "i am not null" | upper | quote}}
  {{"test nindent" | upper}}
  {{.Values.customBlock.auther.adress | nindent 4 }}
  {{.Values.customBlock.auther.adress | nindent 1 }}
  {{- .Values.customBlock.auther.adress | nindent 2 }}
  {{- .Values.customBlock.auther.adress | nindent 6 }}
  {{"test ifStatement" | upper}}
  {{- if .Values.customBlock.auther.bluen}}
    {{- "value is present" | nindent 4}}
  {{- else}}
    {{- "value is not present" | nindent 4}}
  {{- end}}
  {{"test enabled" | upper}}
  {{- if not .Values.customBlock.auther.enabled }}
    {{- "value is present" | nindent 4}}
  {{- else}}
    {{- "'if not' is working. Normally that's true." | nindent 6}}
  {{- end}}

{{"Values From Chart: "}}
  keywords: {{- .Chart.Keywords}}
  Chart Version: {{- .Chart.AppVersion}}
  {{.Chart.Name}}
  {{.Chart.Name}}

 {{"test with function" | upper}}
 {{- with .Values.customBlock.auther2}}
 {{- toYaml . | nindent 2}}
 {{- end}}

 {{- with .Values.ingress.tls}}
 {{- toYaml . | nindent 2}}
 {{- else}}
 {{"tls sections is empty"}}
 {{- end}}

metadata:
  name: {{ include "nginx2.fullname" . }}
  labels:
    {{- include "nginx2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
